### ISSUE TITLE
Interval value.

### ISSUE THREAD

**Issue by philipbaginski** [oleksiyPetlyuk/nova-range-filter#2]
Hi! My question: How to set up interval value?

**Comment by oleksiyPetlyuk** [comment]
> Hi! My question: How to set up interval value?

@philipbaginski Hello!
You can set up an interval in v 0.0.2 by `$this->interval = 20` call in constructor.
Please note that (max - min) should be dividable by the interval.

**Comment by philipbaginski** [comment]
Thank you for tip. I did: min = 0, max. = 6, interval = 0.1
